= About OAuth 2.0
:meta-audience: Developer
:meta-job-phase: Implement
:meta-job:
:meta-exp-level: Expert
:meta-feature: oauth
:meta-keywords: oauth, oauth provider, authentication
:meta-synonym: 
:meta-product: API Manager, Studio, Mule
:meta-applies-to:

In Anypoint Platform, you work with OAuth solutions on the server and client side:

* Accessing an OAuth-protected server from a client app
+
Example: Configure an HTTP or Salesforce connector in the app to access OAuth-protected servers.
+
* Protecting an API from unauthorized calls from client applications
+
Example: To your API, apply an OAuth 2.0 policy and configure an OAuth provider to deny access to unauthenticated client apps.

The following OAuth policies and providers are available for protecting Mule apps:

* PingFederate provider and PingFederate OAuth Token Enforcement policy
* OpenAM provider and OpenAM OAuthToken Enforcement policy
* Mule OAuth 2.0 provider and OAuth 2.0 Access Token Enforcement Using External Provider policy

Using PingFederate or OpenAM is recommended.

// add OpenID Connect

== About the Mule OAuth Provider

If you do not want to contract with an organization, such as PingFederate or OpenAM, you need to build a Mule OAuth provider. The OAuth 2.0 Access Token Enforcement Using External Provider policy supports HTTPS communication using a Mule OAuth 2.0 provider. The provider verifies the validity of OAuth 2.0 credentials. The Mule OAuth provider can run on any application server that is in the same organization as your OAuth-protected API. For example, you can run the Mule provider on premises using a Tomcat server or in the cloud using CloudHub. 

If you are using the deprecated AES OAuth policy provider for non-production environments, the policy as-is is working for you, and can accept tokens exchanged by HTTP (and not HTTPS), no change is required; otherwise, migrate to a Mule OAuth provider as follows:

* Customize the Mule OAuth provider to replace the deprecated one.
+
On Exchange, you can download one provider that supports user/password or another that support LDAP.
+
* Remove policies from the affected APIs.
* Reapply policies.

Your existing registered apps, client IDs, and client secrets continue working.

== See Also

* link:/api-manager/external-oauth-2.0-token-validation-policy[OAuth 2.0 Access Token Enforcement Using External Provider]
* link:/access-management/external-identity[PingFederate and OpenAM providers]
